#pragma config(Sensor, in1,    leftLight,      sensorLineFollower)
#pragma config(Sensor, in2,    middleLight,    sensorLineFollower)
#pragma config(Sensor, in3,    rightLight,     sensorLineFollower)
#pragma config(Sensor, in4,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in5,    kickerPot,      sensorPotentiometer)
#pragma config(Sensor, in6,    hangerPot,      sensorPotentiometer)
#pragma config(Sensor, in7,    gyroSensor,     sensorGyro)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  slideEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port1,           hangerMotor,   tmotorVex393, openLoop)
#pragma config(Motor,  port2,           frontRightMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port4,           rearRightMotor, tmotorVex393, openLoop, encoder, encoderPort, dgtl1, 1000)
#pragma config(Motor,  port5,           rearLeftMotor, tmotorVex393, openLoop, encoder, encoderPort, dgtl3, 1000)
#pragma config(Motor,  port6,           slideMotor,    tmotorVex393, openLoop, encoder, encoderPort, dgtl7, 1000)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393, openLoop)
#pragma config(Motor,  port8,           kickerMotor,   tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
This program is designed to give new programmers beginning code that allows their robots to move from
point to point on the gameboard. The program uses three functions: moveForward, turnRight, and turnLeft
to move around the gameboard.  Each of the functions accepts two paramenters: encoderCounts and speed.

Kickerbot - Basic Movement
- This program assumes that you are using the VEX Kickerbot in the VEX Toss Up Game.
- This program demonstrates basic movements (forward, turn left, turn right) that can be performed
with the Kickerbot using encoder-based programming.
----------------------------------------------------------------------------------------------------*/

//Function to move the robot forward for a specified amount of encoder counts
//at a specified speed
void moveForward(int encoderCounts, int speed)
{
	//Clear the encoders before using them
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder]  = 0;

	//While both of the encoders are less than the specified amount
	while(SensorValue[rightEncoder] < encoderCounts && SensorValue[leftEncoder] < encoderCounts)
	{
		//If the two encoder values are equal
		if(SensorValue[rightEncoder] == SensorValue[leftEncoder])
		{
			//Move the robot forward at the specified speed
			motor[rearRightMotor]  = speed;
			motor[rearLeftMotor]   = speed;
			motor[frontRightMotor] = speed;
			motor[frontLeftMotor]  = speed;
		}

		//If the right encoder is greater than the left encoder (veering to the left)
		else if(SensorValue[rightEncoder] > SensorValue[leftEncoder])
		{
			//Adjust the robot slightly to the right
			motor[rearRightMotor]  = speed;
			motor[rearLeftMotor]   = speed+5;
			motor[frontRightMotor] = speed;
			motor[frontLeftMotor]  = speed+5;
		}

		//If the left encoder is greater than the right encoder (veering to the right)
		else if(SensorValue[rightEncoder] < SensorValue[leftEncoder])
		{
			//Adjust the robot slightly to the right
			motor[rearRightMotor]  = speed+5;
			motor[rearLeftMotor]   = speed;
			motor[frontRightMotor] = speed+5;
			motor[frontLeftMotor]  = speed;
		}
	}

	//Stop the robot
	motor[rearRightMotor]  = 0;
	motor[rearLeftMotor]   = 0;
	motor[frontRightMotor] = 0;
	motor[frontLeftMotor]  = 0;
}

//Turn the robot left for the specified encoder counts
//at a specified speed
void turnLeft(int encoderCounts, int speed)
{
	//Clear the encoders before using them
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder]  = 0;

	//While the absolute value of the right motor's encoder is less
	//than the specified amount
	while(abs(SensorValue[rightEncoder]) < encoderCounts)
	{
		//Turn the robot to the left at the specified speed
		motor[rearRightMotor]  = speed;
		motor[rearLeftMotor]   = -speed;
		motor[frontRightMotor] = speed;
		motor[frontLeftMotor]  = -speed;
	}

	//Stop the robot
	motor[rearRightMotor]  = 0;
	motor[rearLeftMotor]   = 0;
	motor[frontRightMotor] = 0;
	motor[frontLeftMotor]  = 0;
}

//Turn the robot left for the specified encoder counts
//at a specified speed
void turnRight(int encoderCounts, int speed)
{
	//Clear the encoders
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder]  = 0;

	//While the absolute value of the left motor's encoder is less
	//than the specified amount
	while(abs(SensorValue[leftEncoder]) < encoderCounts)
	{
		//Turn the robot to the right at the specified speed
		motor[rearRightMotor]  = -speed;
		motor[rearLeftMotor]   = speed;
		motor[frontRightMotor] = -speed;
		motor[frontLeftMotor]  = speed;
	}

	//Stop the robot
	motor[rearRightMotor]  = 0;
	motor[rearLeftMotor]   = 0;
	motor[frontRightMotor] = 0;
	motor[frontLeftMotor]  = 0;
}

task main()
{
	//Move the robot forward for 1000 encoder counts
	//at a speed of 50, then wait for half of a second
	moveForward(1000, 50);
	wait1Msec(500);

	//Turn the robot to the right for 440 encoder counts
	//at a speed of 25, then wait for half of a second
	turnRight(440, 25);
	wait1Msec(500);

	//Turn the robot to the left for 440 encoder counts
	//at a speed of 25, then wait for half of a second
	turnLeft(440, 25);
	wait1Msec(500);
}
